import { NextRequest, NextResponse } from 'next/server';
import { spawn } from 'child_process';
import { existsSync, readdirSync, readFileSync, mkdirSync, rmSync } from 'fs';
import { tmpdir } from 'os';
import { join } from 'path';
import {
  parseVtt,
  buildTranscript,
  extensionForFormat,
  sanitizeFilename,
  isAutoGeneratedVtt,
  type TranscriptFormat,
} from '@/lib/transcript';

/**
 * Transcript (subtitle/caption) extraction endpoint.
 *
 * ## How it works
 * 1. Client POSTs { url, format, lang }.
 * 2. We use yt-dlp to download the subtitle track into a temp dir
 *    WITHOUT downloading the video (`--skip-download`). We request manual
 *    subtitles first and fall back to auto-generated captions.
 * 3. We read the resulting .vtt file, parse it, and format it into the
 *    requested output (clean text, timestamped, or SRT).
 * 4. The transcript is returned as JSON so the client can save it as a file.
 *
 * ## Why JSON (not a direct file stream)?
 * Returning JSON keeps the client simple (it builds the Blob), lets us send
 * useful metadata (resolved language, cue count, suggested filename), and is
 * trivial to unit-test on both ends.
 */

export const maxDuration = 120;
export const dynamic = 'force-dynamic';

const YT_DLP_PATH = process.env.YT_DLP_PATH || 'yt-dlp';

const YOUTUBE_URL_REGEX =
  /^(https?:\/\/)?(www\.)?(youtube\.com\/(watch\?v=|embed\/|v\/|shorts\/)|youtu\.be\/)[\w-]+/;

const VALID_FORMATS: readonly TranscriptFormat[] = ['txt', 'timestamped', 'srt'];

/** Accept only simple BCP-47-ish language codes to avoid arg injection into yt-dlp. */
const LANG_REGEX = /^[a-zA-Z]{2,3}(-[a-zA-Z0-9]{2,8})?$/;

function validateYouTubeURL(url: string): boolean {
  return YOUTUBE_URL_REGEX.test(url);
}

interface VideoMeta {
  title: string;
  author: string;
}

/**
 * Get the video title and uploader via a lightweight yt-dlp --print call.
 *
 * Metadata is "nice to have" (it only decorates the filename/header), so a
 * failure here never blocks the transcript — we resolve with safe defaults.
 */
function getVideoMeta(url: string): Promise<VideoMeta> {
  const fallback: VideoMeta = { title: 'transcript', author: '' };

  return new Promise((resolve) => {
    const proc = spawn(YT_DLP_PATH, [
      '--print',
      '%(title)s\n%(uploader)s',
      '--no-warnings',
      '--no-check-certificates',
      '--no-playlist',
      url,
    ]);

    let out = '';
    let error = '';

    proc.stdout?.on('data', (data) => {
      out += data.toString();
    });
    proc.stderr?.on('data', (data) => {
      error += data.toString();
    });
    proc.on('close', (code) => {
      if (code === 0 && out.trim()) {
        const [title, author] = out.trim().split('\n');
        resolve({
          title: (title || 'transcript').trim(),
          author: (author || '').trim(),
        });
      } else {
        if (error) console.warn('[TRANSCRIPT] Metadata unavailable:', error.trim());
        resolve(fallback);
      }
    });
    proc.on('error', () => resolve(fallback));
  });
}

/**
 * Download the subtitle track into `tempDir` using yt-dlp.
 *
 * Resolves once yt-dlp exits — even on a non-zero code. yt-dlp commonly
 * exits non-zero when *some* requested languages fail (e.g. a 429 on one
 * track) while still writing a perfectly usable file for another. The caller
 * decides success based on whether a subtitle file was actually produced.
 * We only reject if the process fails to start (e.g. yt-dlp not installed).
 */
function downloadSubtitles(
  url: string,
  lang: string,
  tempDir: string,
): Promise<void> {
  return new Promise((resolve, reject) => {
    const proc = spawn(YT_DLP_PATH, [
      '--skip-download',
      '--write-subs',
      '--write-auto-subs',
      '--sub-langs',
      // e.g. "en.*,en" matches en, en-US, en-orig, etc.
      `${lang}.*,${lang}`,
      '--sub-format',
      'vtt/best',
      '--no-warnings',
      '--no-check-certificates',
      '--no-playlist',
      '-o',
      join(tempDir, 'transcript.%(ext)s'),
      url,
    ]);

    let error = '';
    proc.stderr?.on('data', (data) => {
      error += data.toString();
    });
    proc.on('close', () => {
      if (error) console.warn('[TRANSCRIPT] yt-dlp subtitle warnings:', error.trim());
      resolve();
    });
    proc.on('error', (err) => reject(err));
  });
}

/** Infer the language code from a yt-dlp subtitle filename ("transcript.<lang>.vtt"). */
function languageFromFilename(file: string): string {
  const parts = file.split('.');
  return parts.length >= 3 ? parts[parts.length - 2] : 'unknown';
}

/**
 * Find the best subtitle file in `tempDir`.
 *
 * yt-dlp may write several .vtt files (e.g. a clean manual "en" track plus an
 * auto-generated "en-orig" track full of rolling-caption duplicates). We pick
 * deterministically, preferring:
 *   1. an exact match for the requested language ("en")
 *   2. non-auto tracks (filenames without "orig")
 *   3. the shortest language code
 */
function findSubtitleFile(
  tempDir: string,
  preferredLang: string,
): { path: string; language: string } | null {
  if (!existsSync(tempDir)) return null;

  const candidates = readdirSync(tempDir)
    .filter((f) => f.endsWith('.vtt'))
    .map((file) => ({ file, language: languageFromFilename(file) }));

  if (!candidates.length) return null;

  candidates.sort((a, b) => {
    const exact = Number(b.language === preferredLang) - Number(a.language === preferredLang);
    if (exact) return exact;
    const orig = Number(a.language.includes('orig')) - Number(b.language.includes('orig'));
    if (orig) return orig;
    return a.language.length - b.language.length;
  });

  const best = candidates[0];
  return { path: join(tempDir, best.file), language: best.language };
}

function cleanupTempDir(dir: string): void {
  try {
    if (dir && existsSync(dir)) {
      rmSync(dir, { recursive: true, force: true });
    }
  } catch (error) {
    console.error('[TRANSCRIPT] Failed to clean up temp dir:', error);
  }
}

export async function POST(request: NextRequest) {
  let tempDir = '';

  try {
    const body = await request.json();
    const url: unknown = body.url;
    const rawFormat: unknown = body.format;
    const rawLang: unknown = body.lang;

    if (!url || typeof url !== 'string') {
      return NextResponse.json({ error: 'URL_REQUIRED' }, { status: 400 });
    }

    if (!validateYouTubeURL(url)) {
      return NextResponse.json({ error: 'INVALID_SOURCE_URL' }, { status: 400 });
    }

    const format: TranscriptFormat = VALID_FORMATS.includes(
      rawFormat as TranscriptFormat,
    )
      ? (rawFormat as TranscriptFormat)
      : 'txt';

    const lang =
      typeof rawLang === 'string' && LANG_REGEX.test(rawLang) ? rawLang : 'en';

    console.log('[TRANSCRIPT] Extracting transcript for:', url, { format, lang });

    tempDir = join(tmpdir(), `yt-transcript-${Date.now()}`);
    mkdirSync(tempDir, { recursive: true });

    // Fetch metadata and subtitles in parallel — they're independent.
    const [meta] = await Promise.all([
      getVideoMeta(url),
      downloadSubtitles(url, lang, tempDir),
    ]);

    const subtitle = findSubtitleFile(tempDir, lang);
    if (!subtitle) {
      return NextResponse.json(
        { error: 'NO_TRANSCRIPT_AVAILABLE' },
        { status: 404 },
      );
    }

    const vttContent = readFileSync(subtitle.path, 'utf-8');
    const cues = parseVtt(vttContent);

    if (!cues.length) {
      return NextResponse.json(
        { error: 'NO_TRANSCRIPT_CONTENT' },
        { status: 404 },
      );
    }

    const transcript = buildTranscript(
      cues,
      format,
      {
        title: meta.title,
        author: meta.author,
        url,
        language: subtitle.language,
      },
      { autoGenerated: isAutoGeneratedVtt(vttContent) },
    );

    const base = sanitizeFilename(meta.title);
    const filename = `${base}.${subtitle.language}.${extensionForFormat(format)}`;

    console.log(
      `[TRANSCRIPT] Done: ${filename} (${cues.length} cues, lang=${subtitle.language})`,
    );

    return NextResponse.json({
      transcript,
      filename,
      language: subtitle.language,
      format,
      cueCount: cues.length,
    });
  } catch (error) {
    console.error('[TRANSCRIPT] Error:', error);
    return NextResponse.json(
      {
        error: 'TRANSCRIPT_FAILED',
        details:
          process.env.NODE_ENV === 'development'
            ? error instanceof Error
              ? error.message
              : String(error)
            : undefined,
      },
      { status: 500 },
    );
  } finally {
    cleanupTempDir(tempDir);
  }
}
