/**
 * Transcript parsing & formatting utilities.
 *
 * These are PURE functions (no I/O) so they can be unit-tested in isolation
 * and reused by the /api/transcript route. The route handles fetching the
 * raw subtitle file via yt-dlp; everything here just transforms text.
 *
 * ## The two flavours of YouTube subtitle
 * - **Manual** captions: clean, sentence-per-cue, no overlap. The only
 *   cleanup needed is dropping the occasional exact consecutive duplicate.
 * - **Auto-generated** captions: a "rolling" two-line window where each cue
 *   repeats the tail of the previous cue and appends a few new words, plus
 *   inline word-timing tags like `<00:00:05.120><c> word</c>`. Naively
 *   concatenating these produces a stuttering mess.
 *
 * We detect which flavour we have (auto-captions contain inline timestamp
 * tags; manual ones don't) and de-duplicate accordingly. Crucially we do NOT
 * apply the aggressive word-overlap merge to manual captions, because that
 * would wrongly collapse legitimately repeated lines (e.g. song lyrics).
 */

/** A single subtitle cue with its time range (in seconds) and cleaned text. */
export interface TranscriptCue {
  /** Start time in seconds. */
  start: number;
  /** End time in seconds. */
  end: number;
  /** Cleaned, single-line text (tags and entities removed). */
  text: string;
}

/** Output formats offered to the user. */
export type TranscriptFormat = 'txt' | 'timestamped' | 'srt';

export interface TranscriptMeta {
  title?: string;
  author?: string;
  url?: string;
  language?: string;
}

export interface BuildOptions {
  /** Apply rolling word-overlap de-duplication (for auto-generated captions). */
  autoGenerated?: boolean;
}

/** Characters per line when wrapping the clean-text output. */
const WRAP_WIDTH = 90;

/**
 * Decode the handful of HTML entities that appear in YouTube VTT files.
 * We intentionally keep this small rather than pulling in a full HTML
 * entity decoder — these cover essentially everything seen in captions.
 */
function decodeEntities(text: string): string {
  return text
    .replace(/&amp;/g, '&')
    .replace(/&lt;/g, '<')
    .replace(/&gt;/g, '>')
    .replace(/&#39;/g, "'")
    .replace(/&quot;/g, '"')
    .replace(/&nbsp;/g, ' ');
}

/**
 * Strip WebVTT inline markup from a single line and normalize whitespace.
 *
 * Removes inline timestamp tags (<00:00:05.120>) and styling tags
 * (<c>, </c>, <c.colorE5E5E5>, <v Speaker>), then decodes entities and
 * collapses runs of whitespace.
 */
function cleanLine(line: string): string {
  return decodeEntities(line.replace(/<[^>]+>/g, ''))
    .replace(/\s+/g, ' ')
    .trim();
}

/**
 * Parse a WebVTT timestamp ("HH:MM:SS.mmm" or "MM:SS.mmm") into seconds.
 * Returns NaN if the string isn't a recognizable timestamp.
 */
export function parseTimestamp(stamp: string): number {
  const match = stamp
    .trim()
    .match(/^(?:(\d+):)?(\d{1,2}):(\d{2})(?:[.,](\d{1,3}))?$/);
  if (!match) return NaN;

  const hours = match[1] ? parseInt(match[1], 10) : 0;
  const minutes = parseInt(match[2], 10);
  const seconds = parseInt(match[3], 10);
  const millis = match[4] ? parseInt(match[4].padEnd(3, '0'), 10) : 0;

  return hours * 3600 + minutes * 60 + seconds + millis / 1000;
}

/**
 * Format a number of seconds as "HH:MM:SS" (timestamped output)
 * or "HH:MM:SS,mmm" (SRT output, which requires milliseconds).
 */
export function formatTimestamp(totalSeconds: number, withMillis = false): string {
  const safe = Number.isFinite(totalSeconds) && totalSeconds > 0 ? totalSeconds : 0;
  const whole = Math.floor(safe);
  const hours = Math.floor(whole / 3600);
  const minutes = Math.floor((whole % 3600) / 60);
  const seconds = whole % 60;

  const hh = String(hours).padStart(2, '0');
  const mm = String(minutes).padStart(2, '0');
  const ss = String(seconds).padStart(2, '0');
  const base = `${hh}:${mm}:${ss}`;

  if (!withMillis) return base;

  const millis = Math.round((safe - whole) * 1000);
  return `${base},${String(millis).padStart(3, '0')}`;
}

/**
 * True if the VTT content looks like a YouTube auto-generated caption track,
 * detected by the presence of inline word-timing tags (e.g. "<00:00:05.120>").
 * Manual subtitle tracks don't contain these.
 */
export function isAutoGeneratedVtt(content: string): boolean {
  return /<\d{1,2}:\d{2}:\d{2}[.,]\d{1,3}>/.test(content);
}

/**
 * Parse the body of a WebVTT file into structured cues.
 *
 * Lenient by design: ignores the header (WEBVTT, Kind, Language), NOTE/STYLE
 * blocks, and optional numeric cue identifiers, and tolerates the cue-setting
 * suffixes YouTube appends after the end time (e.g. "align:start position:0%").
 * Cues whose text is empty after cleaning are dropped.
 */
export function parseVtt(content: string): TranscriptCue[] {
  if (!content || !content.trim()) return [];

  const blocks = content.replace(/\r\n/g, '\n').replace(/\r/g, '\n').split(/\n\s*\n/);
  const cues: TranscriptCue[] = [];
  const TIMING =
    /(\d{1,2}:\d{1,2}:\d{2}(?:[.,]\d{1,3})?|\d{1,2}:\d{2}(?:[.,]\d{1,3})?)\s*-->\s*(\d{1,2}:\d{1,2}:\d{2}(?:[.,]\d{1,3})?|\d{1,2}:\d{2}(?:[.,]\d{1,3})?)/;

  for (const block of blocks) {
    const lines = block.split('\n');

    if (/^WEBVTT/.test(lines[0]) || /^(NOTE|STYLE)\b/.test(lines[0])) {
      continue;
    }

    const timingIndex = lines.findIndex((l) => TIMING.test(l));
    if (timingIndex === -1) continue;

    const timingMatch = lines[timingIndex].match(TIMING)!;
    const start = parseTimestamp(timingMatch[1]);
    const end = parseTimestamp(timingMatch[2]);
    if (Number.isNaN(start) || Number.isNaN(end)) continue;

    const text = lines
      .slice(timingIndex + 1)
      .map(cleanLine)
      .filter(Boolean)
      .join(' ')
      .replace(/\s+/g, ' ')
      .trim();

    if (text) {
      cues.push({ start, end, text });
    }
  }

  return cues;
}

/**
 * Drop exact consecutive duplicate cues, and cues fully contained in their
 * neighbour. Safe for *manual* captions: it removes the occasional repeated
 * line without touching legitimately recurring text elsewhere in the track.
 */
export function dedupeConsecutive(cues: TranscriptCue[]): TranscriptCue[] {
  const result: TranscriptCue[] = [];

  for (const cue of cues) {
    const prev = result[result.length - 1];
    if (prev) {
      if (prev.text === cue.text) continue;
      if (prev.text.endsWith(cue.text)) continue;
      if (cue.text.startsWith(prev.text)) {
        result[result.length - 1] = { ...cue, start: prev.start };
        continue;
      }
    }
    result.push(cue);
  }

  return result;
}

/** Normalize a word for overlap comparison (case- and trailing-punctuation-insensitive). */
function normalizeWord(word: string): string {
  return word.toLowerCase().replace(/[.,!?;:]+$/, '');
}

/**
 * Collapse the "rolling" overlap in YouTube auto-generated captions using
 * word-level de-duplication.
 *
 * Each cue typically repeats the last few words of the previous cue before
 * adding new ones. For every cue we find the longest run where the tail of
 * the text emitted so far matches the head of the incoming cue, and keep only
 * the genuinely new words. Comparison is case-insensitive; the original words
 * (with punctuation/casing) are preserved in the output.
 */
export function dedupeRolling(cues: TranscriptCue[]): TranscriptCue[] {
  const out: TranscriptCue[] = [];
  // Sliding window of recently emitted words (normalized), bounded for cost.
  let tail: string[] = [];
  const MAX_TAIL = 60;

  for (const cue of cues) {
    const words = cue.text.split(' ').filter(Boolean);
    if (!words.length) continue;

    const normWords = words.map(normalizeWord);
    const maxK = Math.min(tail.length, words.length);

    let overlap = 0;
    for (let k = maxK; k > 0; k--) {
      const tailSlice = tail.slice(tail.length - k).join(' ');
      const headSlice = normWords.slice(0, k).join(' ');
      if (tailSlice === headSlice) {
        overlap = k;
        break;
      }
    }

    const newWords = words.slice(overlap);
    if (!newWords.length) continue;

    out.push({ start: cue.start, end: cue.end, text: newWords.join(' ') });

    tail.push(...newWords.map(normalizeWord));
    if (tail.length > MAX_TAIL) tail = tail.slice(-MAX_TAIL);
  }

  return out;
}

/** Word-wrap a long string to the given width without breaking words. */
function wrapText(text: string, width = WRAP_WIDTH): string {
  const words = text.split(/\s+/).filter(Boolean);
  const lines: string[] = [];
  let line = '';

  for (const word of words) {
    if (!line) {
      line = word;
    } else if (line.length + 1 + word.length <= width) {
      line += ` ${word}`;
    } else {
      lines.push(line);
      line = word;
    }
  }
  if (line) lines.push(line);

  return lines.join('\n');
}

/** Build a small header block for the text-based formats. */
function buildHeader(meta: TranscriptMeta): string[] {
  const header: string[] = [];
  if (meta.title) header.push(`# ${meta.title}`);
  if (meta.author) header.push(`# Channel: ${meta.author}`);
  if (meta.url) header.push(`# Source: ${meta.url}`);
  if (meta.language) header.push(`# Language: ${meta.language}`);
  return header;
}

function withHeader(body: string, meta: TranscriptMeta): string {
  const header = buildHeader(meta);
  return header.length ? `${header.join('\n')}\n\n${body}\n` : `${body}\n`;
}

/**
 * Clean, readable transcript: cues joined into flowing prose and word-wrapped.
 * Expects already-deduplicated cues (see buildTranscript).
 */
export function cuesToPlainText(cues: TranscriptCue[], meta: TranscriptMeta = {}): string {
  const prose = cues
    .map((c) => c.text)
    .join(' ')
    .replace(/\s+/g, ' ')
    .trim();
  return withHeader(wrapText(prose), meta);
}

/**
 * Transcript with "[HH:MM:SS] text" prefixes for easy navigation.
 * Expects already-deduplicated cues (see buildTranscript).
 */
export function cuesToTimestamped(cues: TranscriptCue[], meta: TranscriptMeta = {}): string {
  const body = cues.map((c) => `[${formatTimestamp(c.start)}] ${c.text}`).join('\n');
  return withHeader(body, meta);
}

/**
 * Standard SubRip (.srt) output for use in video editors.
 * Cues are re-numbered sequentially. We do NOT merge/dedupe here because SRT
 * is meant to map 1:1 to the on-screen timing.
 */
export function cuesToSrt(cues: TranscriptCue[]): string {
  return (
    cues
      .map((cue, i) => {
        const start = formatTimestamp(cue.start, true);
        const end = formatTimestamp(cue.end, true);
        return `${i + 1}\n${start} --> ${end}\n${cue.text}`;
      })
      .join('\n\n') + (cues.length ? '\n' : '')
  );
}

/**
 * Format parsed cues into the requested output format.
 *
 * For txt/timestamped, cues are de-duplicated first — using the rolling
 * word-overlap merge for auto-generated captions, or the lighter consecutive
 * de-dupe for manual ones. SRT keeps the raw 1:1 timing.
 *
 * Throws NO_TRANSCRIPT_CONTENT if there are no cues, so the route can return
 * a clear error.
 */
export function buildTranscript(
  cues: TranscriptCue[],
  format: TranscriptFormat,
  meta: TranscriptMeta = {},
  options: BuildOptions = {},
): string {
  if (!cues.length) {
    throw new Error('NO_TRANSCRIPT_CONTENT');
  }

  if (format === 'srt') {
    return cuesToSrt(cues);
  }

  const deduped = options.autoGenerated ? dedupeRolling(cues) : dedupeConsecutive(cues);

  return format === 'timestamped'
    ? cuesToTimestamped(deduped, meta)
    : cuesToPlainText(deduped, meta);
}

/** File extension for a given transcript format. */
export function extensionForFormat(format: TranscriptFormat): string {
  return format === 'srt' ? 'srt' : 'txt';
}

/**
 * Turn an arbitrary video title into a safe filename base.
 * Mirrors the conservative sanitization used elsewhere in the app.
 */
export function sanitizeFilename(title: string): string {
  const cleaned = title
    .replace(/[^\w\s-]/g, '')
    .trim()
    .replace(/\s+/g, ' ');
  return cleaned || 'transcript';
}
