import { describe, it, expect } from 'vitest';
import {
  parseTimestamp,
  formatTimestamp,
  parseVtt,
  isAutoGeneratedVtt,
  dedupeConsecutive,
  dedupeRolling,
  cuesToPlainText,
  cuesToTimestamped,
  cuesToSrt,
  buildTranscript,
  extensionForFormat,
  sanitizeFilename,
  type TranscriptCue,
} from './transcript';

/**
 * Tests for the transcript parsing/formatting utilities.
 *
 * These are pure functions, so we can exercise the messy real-world inputs
 * (YouTube auto-caption tags, rolling duplicates, malformed timestamps)
 * directly without any I/O or yt-dlp.
 */

describe('parseTimestamp', () => {
  it('parses HH:MM:SS.mmm', () => {
    expect(parseTimestamp('01:02:03.500')).toBeCloseTo(3723.5, 3);
  });

  it('parses MM:SS.mmm (no hours)', () => {
    expect(parseTimestamp('02:05.250')).toBeCloseTo(125.25, 3);
  });

  it('parses timestamps without milliseconds', () => {
    expect(parseTimestamp('00:00:10')).toBe(10);
  });

  it('accepts a comma as the millisecond separator (SRT style)', () => {
    expect(parseTimestamp('00:00:01,500')).toBeCloseTo(1.5, 3);
  });

  it('returns NaN for garbage input', () => {
    expect(parseTimestamp('not-a-time')).toBeNaN();
    expect(parseTimestamp('')).toBeNaN();
  });
});

describe('formatTimestamp', () => {
  it('formats seconds as HH:MM:SS by default', () => {
    expect(formatTimestamp(3723)).toBe('01:02:03');
  });

  it('zero-pads correctly', () => {
    expect(formatTimestamp(5)).toBe('00:00:05');
  });

  it('includes milliseconds when requested (SRT)', () => {
    expect(formatTimestamp(1.5, true)).toBe('00:00:01,500');
  });

  it('clamps negative or non-finite values to zero', () => {
    expect(formatTimestamp(-10)).toBe('00:00:00');
    expect(formatTimestamp(NaN)).toBe('00:00:00');
  });
});

describe('parseVtt', () => {
  it('parses a basic WebVTT file', () => {
    const vtt = `WEBVTT

00:00:00.000 --> 00:00:04.000
Hello world

00:00:04.000 --> 00:00:08.000
This is a test`;

    const cues = parseVtt(vtt);
    expect(cues).toHaveLength(2);
    expect(cues[0]).toEqual({ start: 0, end: 4, text: 'Hello world' });
    expect(cues[1]).toEqual({ start: 4, end: 8, text: 'This is a test' });
  });

  it('strips inline timing tags and <c> styling tags from auto-captions', () => {
    const vtt = `WEBVTT
Kind: captions
Language: en

00:00:01.000 --> 00:00:03.000
hello<00:00:01.500><c> there</c> friend`;

    const cues = parseVtt(vtt);
    expect(cues).toHaveLength(1);
    expect(cues[0].text).toBe('hello there friend');
  });

  it('decodes HTML entities', () => {
    const vtt = `WEBVTT

00:00:00.000 --> 00:00:02.000
Tom &amp; Jerry said &quot;hi&quot;`;

    const cues = parseVtt(vtt);
    expect(cues[0].text).toBe('Tom & Jerry said "hi"');
  });

  it('ignores NOTE and STYLE blocks', () => {
    const vtt = `WEBVTT

NOTE This is a comment block

STYLE
::cue { color: white }

00:00:00.000 --> 00:00:02.000
Real content`;

    const cues = parseVtt(vtt);
    expect(cues).toHaveLength(1);
    expect(cues[0].text).toBe('Real content');
  });

  it('handles numeric cue identifiers preceding the timing line', () => {
    const vtt = `WEBVTT

1
00:00:00.000 --> 00:00:02.000
First

2
00:00:02.000 --> 00:00:04.000
Second`;

    const cues = parseVtt(vtt);
    expect(cues.map((c) => c.text)).toEqual(['First', 'Second']);
  });

  it('tolerates cue-setting suffixes after the end time', () => {
    const vtt = `WEBVTT

00:00:00.000 --> 00:00:02.000 align:start position:0%
Positioned text`;

    const cues = parseVtt(vtt);
    expect(cues).toHaveLength(1);
    expect(cues[0].text).toBe('Positioned text');
  });

  it('joins multi-line cue text into a single line', () => {
    const vtt = `WEBVTT

00:00:00.000 --> 00:00:03.000
line one
line two`;

    const cues = parseVtt(vtt);
    expect(cues[0].text).toBe('line one line two');
  });

  // ── Unhappy paths ────────────────────────────────────────────────────
  it('returns an empty array for empty input', () => {
    expect(parseVtt('')).toEqual([]);
    expect(parseVtt('   ')).toEqual([]);
  });

  it('returns an empty array when there are no timing lines', () => {
    expect(parseVtt('WEBVTT\n\njust some text\nwith no timings')).toEqual([]);
  });

  it('skips cues whose text is empty after stripping tags', () => {
    const vtt = `WEBVTT

00:00:00.000 --> 00:00:02.000
<00:00:01.000><c></c>

00:00:02.000 --> 00:00:04.000
Real`;

    const cues = parseVtt(vtt);
    expect(cues).toHaveLength(1);
    expect(cues[0].text).toBe('Real');
  });
});

describe('isAutoGeneratedVtt', () => {
  it('detects inline word-timing tags as auto-generated', () => {
    expect(
      isAutoGeneratedVtt('WEBVTT\n\n00:00:00.000 --> 00:00:02.000\nhi<00:00:01.000><c> there</c>'),
    ).toBe(true);
  });

  it('treats a plain manual track as not auto-generated', () => {
    expect(
      isAutoGeneratedVtt('WEBVTT\n\n00:00:00.000 --> 00:00:02.000\nhello world'),
    ).toBe(false);
  });
});

describe('dedupeConsecutive (manual captions)', () => {
  it('drops exact consecutive duplicates', () => {
    const cues: TranscriptCue[] = [
      { start: 0, end: 2, text: 'same line' },
      { start: 2, end: 4, text: 'same line' },
      { start: 4, end: 6, text: 'next line' },
    ];
    expect(dedupeConsecutive(cues).map((c) => c.text)).toEqual([
      'same line',
      'next line',
    ]);
  });

  it('collapses simple prefix-containment duplicates', () => {
    const cues: TranscriptCue[] = [
      { start: 0, end: 2, text: 'the quick brown fox' },
      { start: 2, end: 4, text: 'the quick brown fox jumps over' },
    ];
    expect(dedupeConsecutive(cues).map((c) => c.text)).toEqual([
      'the quick brown fox jumps over',
    ]);
  });

  it('preserves legitimately repeated non-consecutive lines (e.g. lyrics)', () => {
    const cues: TranscriptCue[] = [
      { start: 0, end: 2, text: 'never gonna give you up' },
      { start: 2, end: 4, text: 'never gonna let you down' },
      { start: 4, end: 6, text: 'never gonna give you up' },
    ];
    // None are consecutive exact dups, so all are kept.
    expect(dedupeConsecutive(cues)).toHaveLength(3);
  });
});

describe('dedupeRolling (auto-generated captions)', () => {
  it('merges the rolling word overlap between cues', () => {
    const cues: TranscriptCue[] = [
      { start: 0, end: 2, text: "We're no strangers to love. You know the rules and so do" },
      { start: 2, end: 4, text: 'You know the rules and so do I. I feel commitments' },
      { start: 4, end: 6, text: 'I feel commitments of what I am thinking' },
    ];

    const merged = dedupeRolling(cues);
    const joined = merged.map((c) => c.text).join(' ');
    expect(joined).toBe(
      "We're no strangers to love. You know the rules and so do I. I feel commitments of what I am thinking",
    );
  });

  it('keeps the start time of the cue that introduced the new words', () => {
    const cues: TranscriptCue[] = [
      { start: 10, end: 12, text: 'hello world' },
      { start: 12, end: 14, text: 'world again now' },
    ];
    const merged = dedupeRolling(cues);
    expect(merged).toEqual([
      { start: 10, end: 12, text: 'hello world' },
      { start: 12, end: 14, text: 'again now' },
    ]);
  });

  it('drops a cue that adds no new words', () => {
    const cues: TranscriptCue[] = [
      { start: 0, end: 2, text: 'hello there' },
      { start: 2, end: 4, text: 'hello there' },
    ];
    expect(dedupeRolling(cues)).toHaveLength(1);
  });

  it('matches overlap case-insensitively', () => {
    const cues: TranscriptCue[] = [
      { start: 0, end: 2, text: 'the End' },
      { start: 2, end: 4, text: 'the end is near' },
    ];
    expect(dedupeRolling(cues).map((c) => c.text)).toEqual(['the End', 'is near']);
  });
});

describe('cuesToPlainText', () => {
  it('joins cues into wrapped flowing prose', () => {
    const cues: TranscriptCue[] = [
      { start: 0, end: 2, text: 'Hello world.' },
      { start: 2, end: 4, text: 'This is a transcript.' },
    ];
    expect(cuesToPlainText(cues)).toBe('Hello world. This is a transcript.\n');
  });

  it('wraps long text without breaking words', () => {
    const word = 'lorem';
    const cues: TranscriptCue[] = [
      { start: 0, end: 2, text: Array(40).fill(word).join(' ') },
    ];
    const text = cuesToPlainText(cues).trimEnd();
    const lines = text.split('\n');
    expect(lines.length).toBeGreaterThan(1);
    for (const line of lines) {
      expect(line.length).toBeLessThanOrEqual(90);
    }
  });

  it('includes a metadata header when provided', () => {
    const cues: TranscriptCue[] = [{ start: 0, end: 2, text: 'hello' }];
    const text = cuesToPlainText(cues, {
      title: 'My Video',
      author: 'Creator',
      url: 'https://youtu.be/abc',
      language: 'en',
    });

    expect(text).toContain('# My Video');
    expect(text).toContain('# Channel: Creator');
    expect(text).toContain('# Source: https://youtu.be/abc');
    expect(text).toContain('# Language: en');
    expect(text).toContain('hello');
  });
});

describe('cuesToTimestamped', () => {
  it('prefixes each line with [HH:MM:SS]', () => {
    const cues: TranscriptCue[] = [
      { start: 0, end: 2, text: 'first' },
      { start: 65, end: 70, text: 'second' },
    ];

    const text = cuesToTimestamped(cues);
    expect(text).toContain('[00:00:00] first');
    expect(text).toContain('[00:01:05] second');
  });
});

describe('cuesToSrt', () => {
  it('produces sequentially numbered SRT cues with millisecond timing', () => {
    const cues: TranscriptCue[] = [
      { start: 0, end: 2.5, text: 'first' },
      { start: 2.5, end: 5, text: 'second' },
    ];

    const srt = cuesToSrt(cues);
    expect(srt).toBe(
      '1\n00:00:00,000 --> 00:00:02,500\nfirst\n\n' +
        '2\n00:00:02,500 --> 00:00:05,000\nsecond\n',
    );
  });

  it('returns an empty string for no cues', () => {
    expect(cuesToSrt([])).toBe('');
  });
});

describe('buildTranscript', () => {
  const cues: TranscriptCue[] = [{ start: 0, end: 2, text: 'hi' }];

  it('routes to plain text for "txt"', () => {
    expect(buildTranscript(cues, 'txt')).toBe('hi\n');
  });

  it('routes to timestamped for "timestamped"', () => {
    expect(buildTranscript(cues, 'timestamped')).toBe('[00:00:00] hi\n');
  });

  it('routes to SRT for "srt"', () => {
    expect(buildTranscript(cues, 'srt')).toBe('1\n00:00:00,000 --> 00:00:02,000\nhi\n');
  });

  it('throws when there are no cues', () => {
    expect(() => buildTranscript([], 'txt')).toThrow('NO_TRANSCRIPT_CONTENT');
  });

  it('applies rolling dedup for auto-generated captions', () => {
    const rolling: TranscriptCue[] = [
      { start: 0, end: 2, text: 'hello world' },
      { start: 2, end: 4, text: 'world again' },
    ];
    expect(buildTranscript(rolling, 'txt', {}, { autoGenerated: true })).toBe(
      'hello world again\n',
    );
  });

  it('applies only consecutive dedup for manual captions (keeps overlap words)', () => {
    const manual: TranscriptCue[] = [
      { start: 0, end: 2, text: 'hello world' },
      { start: 2, end: 4, text: 'world again' },
    ];
    // No rolling merge → both cues kept verbatim and joined.
    expect(buildTranscript(manual, 'txt')).toBe('hello world world again\n');
  });

  it('ignores the autoGenerated flag for SRT (1:1 timing preserved)', () => {
    const rolling: TranscriptCue[] = [
      { start: 0, end: 2, text: 'hello world' },
      { start: 2, end: 4, text: 'world again' },
    ];
    const srt = buildTranscript(rolling, 'srt', {}, { autoGenerated: true });
    expect(srt).toContain('hello world');
    expect(srt).toContain('world again');
  });
});

describe('extensionForFormat', () => {
  it('returns srt for the srt format', () => {
    expect(extensionForFormat('srt')).toBe('srt');
  });

  it('returns txt for text formats', () => {
    expect(extensionForFormat('txt')).toBe('txt');
    expect(extensionForFormat('timestamped')).toBe('txt');
  });
});

describe('sanitizeFilename', () => {
  it('strips characters unsafe for filenames', () => {
    expect(sanitizeFilename('My: Video / Title?')).toBe('My Video Title');
  });

  it('collapses whitespace', () => {
    expect(sanitizeFilename('a   b\t c')).toBe('a b c');
  });

  it('falls back to "transcript" when nothing is left', () => {
    expect(sanitizeFilename('***')).toBe('transcript');
    expect(sanitizeFilename('')).toBe('transcript');
  });
});
